name = "x3dh"
version = "0.1.0"
defaultTargets = ["x3dh"]

[[lean_lib]]
name = "X3dh"

[[lean_lib]]
name = "Util"

[[lean_exe]]
name = "x3dh"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
